### ISSUE TITLE
Saving name in Japanese characters results in "???"

### ISSUE THREAD

**Issue by ghost** [WordPress/wordcamp.org#590]
Imported from https://meta.trac.wordpress.org/ticket/2027 
Created by [@Nao](https://profiles.wordpress.org/Nao/):

Steps to reproduce:

1. Go to your Edit Profile page within a WordCamp.org site.
2. Type in some Japanese characters in any of the name fields. e.g. 高野直子
3. Update profile (save).
4. Check the name field - each character is saved as a question mark.

**Comment by ghost** [comment]
Comment by [@Nao](https://profiles.wordpress.org/Nao/):
 * [profile.png](https://meta.trac.wordpress.org/attachment/ticket/2027/profile.png) added

**Comment by ghost** [comment]
Comment by [@Nao](https://profiles.wordpress.org/Nao/):
 * [profile-garbled.png](https://meta.trac.wordpress.org/attachment/ticket/2027/profile-garbled.png) added

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/2027#comment:1) by @iandunn:
 * Status set to `accepted`
 * Owner set to @iandunn

I was able to reproduce this.

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/2027#comment:2) by [@Takahashi_Fumiki](https://profiles.wordpress.org/Takahashi_Fumiki/):

https://meta.trac.wordpress.org/ticket/2746 was marked as a duplicate.

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/2027#comment:3) by @iandunn:
 * Status set to `assigned`
 * Owner cleared

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/2027#comment:4) by slackbot:

_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #meta-wordcamp by iandunn. [View the logs](https://wordpress.slack.com/archives/meta-wordcamp/p1582223239283200)._

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/2027#comment:5) by slackbot:

_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #meta-wordcamp by casiepa. [View the logs](https://wordpress.slack.com/archives/meta-wordcamp/p1591897110435300)._

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/2027#comment:6) by @dd32:

Users really shouldn't edit their User profile via WordCamp (But I realise the need to, since most organisers might not know where else to change their Display Name, etc), but disabling that page is probably more trouble than it's worth.

This would probably be fixed by my recent charset HyperDB fixes once ported to WordCamp.

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/2027#comment:7) by slackbot:

_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #meta-wordcamp by ryelle. [View the logs](https://wordpress.slack.com/archives/meta-wordcamp/p1598895073004500)._

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/2027#comment:8) by @ryelle:

@dd32 Do you know if the HyperDB changes you mentioned above were ported to WordCamp.org? 

I'm still seeing this bug, and we had another report of the name "Levänen" not displaying correctly (not totally sure if it's the same issue).

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/2027#comment:8.9) by @dd32:

Replying to @ryelle:
> dd32 Do you know if the HyperDB changes you mentioned above were ported to WordCamp.org? 

They haven't been ported to WordCamp.org - In order to do that, WordCamp needs to drop the public HyperDB plugin in favour of the WordPress.org variant.
In my testing, it was a drop-in replacement, but I wasn't willing to change it at the time due to inability to test some changes.

**Comment by dd32** [comment]
This is still an issue, after being reported on Slack:
https://wordpress.slack.com/archives/C02QB8GMM/p1712564872970809

WordCamp additionally doesn't have the same object cache loaded, so it can't clear the user caches on w.org, resulting in different data in the DB vs `get_user_by()` when cached.

We should just disable editing these fields.

**Comment by dd32** [comment]
You can't edit user fields anymore on WordCamp, but the display of names should be resolved now :)

This was resolved by switching the HyperDB config to one that respected the `latin1` charset for the users DB, rather than the `utf8mb4` used by WordCamp DB.
